# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ede0b3e8f136361b1051f2b03e70d64c2df3b30e659ef9f7ee56c5884bfc7f0359bb9c18df05b8c8032684348a9784c48a3129555273c5b2af74e8a82c07c3de

test:
  secret_key_base: d1e63af93bbb3c0d04bd879626281d03891801044bf02907c978d380d0d173c5f474c7c68c6d6ea372638b9484039e4c6a0351f0989571d2bda024370b84f37b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
